(set-info :source |printed by MathSAT|)
(declare-fun _OK___AT0 () Bool)
(declare-fun time__AT0 () Int)
(declare-fun xite__AT0 () Int)
(declare-fun flby__AT0 () Int)
(declare-fun param__init___AT0 () Int)
(declare-fun _OK___AT1 () Bool)
(declare-fun time__AT1 () Int)
(declare-fun xite__AT1 () Int)
(declare-fun flby__AT1 () Int)
(define-fun .def_10 () Int (! flby__AT0 :next flby__AT1))
(define-fun .def_23 () Bool (= .def_10 0))
(define-fun .def_8 () Int (! time__AT0 :next time__AT1))
(define-fun .def_21 () Bool (= .def_8 .def_10))
(define-fun .def_18 () Bool (<= 0 .def_8))
(define-fun .def_19 () Bool (not .def_18))
(define-fun .def_7 () Bool (! _OK___AT0 :next _OK___AT1 :invar-property 0))
(define-fun .def_20 () Bool (= .def_7 .def_19))
(define-fun .def_22 () Bool (and .def_20 .def_21))
(define-fun .def_24 () Bool (! (and .def_22 .def_23) :init true))
(define-fun .def_43 () Bool (= time__AT1 flby__AT1))
(define-fun .def_40 () Bool (<= 0 time__AT1))
(define-fun .def_41 () Bool (not .def_40))
(define-fun .def_42 () Bool (= _OK___AT1 .def_41))
(define-fun .def_44 () Bool (and .def_42 .def_43))
(define-fun .def_45 () Bool (and .def_22 .def_44))
(define-fun .def_38 () Bool (= xite__AT1 flby__AT1))
(define-fun .def_32 () Bool (= .def_8 5))
(define-fun .def_35 () Bool (not .def_32))
(define-fun .def_34 () Bool (= xite__AT1 0))
(define-fun .def_36 () Bool (or .def_34 .def_35))
(define-fun .def_28 () Int (* (- 1) xite__AT1))
(define-fun .def_29 () Int (+ .def_8 .def_28))
(define-fun .def_30 () Bool (= .def_29 (- 1)))
(define-fun .def_33 () Bool (or .def_30 .def_32))
(define-fun .def_37 () Bool (and .def_33 .def_36))
(define-fun .def_39 () Bool (and .def_37 .def_38))
(define-fun .def_46 () Bool (! (and .def_39 .def_45) :trans true))
(define-fun .def_9 () Int (! xite__AT0 :next xite__AT1))
(define-fun .def_11 () Int (! param__init___AT0 :next param__init___AT1))
(assert true)
