on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip jsonschema

    - name: Checkout AVR
      uses: actions/checkout@v4
      with:
        repository: aman-goel/avr
        path: deps/avr
        ref: hwmcc20

    - name: Checkout btor2tools
      uses: actions/checkout@v4
      with:
        repository: Boolector/btor2tools
        path: deps/btor2tools

    - name: Install btor2tools
      run: |
        cd deps/btor2tools
        ./configure.sh
        cd build
        make
        cp bin/catbtor ../../
        sudo cp lib/libbtor2parser.so /lib

    - name: mc-moxi
      run: |
        cd test/
        python3 test.py mc-moxi-avr.json

    - name: sortcheck
      run: |
        cd test/
        python3 test.py sortcheck.json

    - name: moxi2btor
      run: |
        cd test/
        python3 test.py moxi2btor.json

    - name: smv2moxi
      run: |
        cd test/
        python3 test.py smv2moxi.json

    - name: smv2btor
      run: |
        cd test/
        python3 test.py smv2btor.json

    - name: vmt2moxi
      run: |
        cd test/
        python3 test.py vmt2moxi.json

    - name: smv2json
      run: |
        cd test/
        python3 test.py smv2json.json
